version: '3.8'

services:
  webapp-counter-service:
    build: .
    container_name: webapp-counter-service
    restart: always
    volumes:
      - data:/data
    ports:
      - '80:8080'

volumes:
  data:
