version: 2.1

jobs:
  test:
    docker:
      - image: python:3.12-slim-bookworm
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install -r requirements.txt
      - run:
          name: Run test
          command: pytest ./src/test-webapp.py

workflows:
  test_build_deploy:
    jobs:
      - test