version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.12.2
        auth:
          username: $DOCKER_REGISTRY_USER
          password: $DOCKER_REGISTRY_PASS
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest ./src/test-webapp.py
  build:
    docker:
      - image: cimg/base:2024.02
        auth:
          username: $DOCKER_REGISTRY_USER
          password: $DOCKER_REGISTRY_PASS
    resource_class: medium
    environment:
      TAG: 0.0.<< pipeline.number >>
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build and push Docker image
          command: |
            echo $DOCKER_REGISTRY_PASS | docker login -u $DOCKER_REGISTRY_USER --password-stdin
            docker buildx create --use
            docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t $DOCKER_REGISTRY_USER/$CIRCLE_PROJECT_REPONAME:$TAG --push .
            docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t $DOCKER_REGISTRY_USER/$CIRCLE_PROJECT_REPONAME --push .
  prepare-infrastructure:
    docker:
      - image: cimg/base:2024.02
        auth:
          username: $DOCKER_REGISTRY_USER
          password: $DOCKER_REGISTRY_PASS
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install Terraform
          command: |
            sudo su
            apt update && apt install terraform -y
      - run:
          name: Initialize Terraform
          command: |
            cd ./terraform
            terraform init

  deploy:
    docker:
      - image: cimg/base:2024.02
        auth:
          username: $DOCKER_REGISTRY_USER
          password: $DOCKER_REGISTRY_PASS
    resource_class: small
    steps:
      - checkout
      - run:
          name: Deploy Over SSH
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "
            docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASS &&
            docker container stop $CIRCLE_PROJECT_REPONAME || true &&
            docker container rm $CIRCLE_PROJECT_REPONAME || true &&
            docker pull $DOCKER_REGISTRY_USER/$CIRCLE_PROJECT_REPONAME &&
            docker run --name $CIRCLE_PROJECT_REPONAME -v data:/data -p 80:8080 -d $DOCKER_REGISTRY_USER/$CIRCLE_PROJECT_REPONAME"

workflows:
  test_build_deploy:
    jobs:
      - test
      - prepare-infrastructure:
          requires:
            - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build