version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.12.2
        auth:
          username: $DOCKER_REGISTRY_USER
          password: $DOCKER_REGISTRY_PASS
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest ./src/test-webapp.py
  build:
    docker:
      - image: cimg/base:2024.02
        auth:
          username: $DOCKER_REGISTRY_USER
          password: $DOCKER_REGISTRY_PASS
    resource_class: medium
    environment:
      TAG: 0.0.<< pipeline.number >>
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build and push Docker image
          command: |
            echo $DOCKER_REGISTRY_PASS | docker login -u $DOCKER_REGISTRY_USER --password-stdin
            docker buildx create --use
            docker buildx build --platform linux/amd64,linux/arm64 -t $DOCKER_REGISTRY_USER/$CIRCLE_PROJECT_REPONAME:$TAG --push .
            docker buildx build --platform linux/amd64,linux/arm64 -t $DOCKER_REGISTRY_USER/$CIRCLE_PROJECT_REPONAME --push .
  deploy:
    docker:
      - image: cimg/base:2024.02
        auth:
          username: $DOCKER_REGISTRY_USER
          password: $DOCKER_REGISTRY_PASS
    resource_class: small
    steps:
      - checkout
      - run:
          name: Deploy Over SSH
          command: |
            mkdir -p ~/.ssh
            echo "$WCS_SERVER_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 400 ~/.ssh/id_rsa
            ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $EC2_USER@$WCS_SERVER_PUBLIC_IP "
            docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASS &&
            docker container stop $CIRCLE_PROJECT_REPONAME || true &&
            docker container rm $CIRCLE_PROJECT_REPONAME || true &&
            docker pull $DOCKER_REGISTRY_USER/$CIRCLE_PROJECT_REPONAME &&
            docker run --name $CIRCLE_PROJECT_REPONAME -v data:/data -p 80:8080 -d $DOCKER_REGISTRY_USER/$CIRCLE_PROJECT_REPONAME"

workflows:
  test_build_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main